version: '3.3'
services:
  nextjs:
    build: .
    working_dir: /app
    command: sh -c "npm install && npm run build && npm run start"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
