'use client';

import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import './globals.css';
import Header from './_components/Header';
import Footer from './_components/Footer';
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton,
} from '@clerk/nextjs';
import { CartContext } from './_context/CartContext';
import { useState } from 'react';
// Import styles of packages that you've installed.
// All packages except `@mantine/hooks` require styles imports
import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';

import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from '@mantine/core';
import { Notifications } from '@mantine/notifications';

const outfit = Outfit({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [cart, setCart] = useState([]);

  return (
    <ClerkProvider>
      <CartContext.Provider value={{ cart, setCart }}>
        <html lang='en' {...mantineHtmlProps}>
          <head>
            <ColorSchemeScript />
          </head>
          <body className={outfit.className}>
            <MantineProvider>
              <Notifications />
              <Header />
              {children}
              <Footer />
            </MantineProvider>
          </body>
        </html>
      </CartContext.Provider>
    </ClerkProvider>
  );
}
